# Script to make a PR if the push is from hhslepicka.
name: auto-pr.yml

on:
  push:
    branches-ignore: main

jobs:
  create-pull-request:
    if: ${{ github.triggering_actor == 'hhslepicka' }}

    runs-on: Ubuntu-latest

    steps:
      - uses: actions/checkout@v4


      - run: gh pr create -B main -H ${{ github.ref_name }} --title "${{ github.ref_name }}" --body "${{ github.event.head_commit.message }}"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}