name: publish workflow

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to publish'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Publishing - ${{ inputs.tag }}
        run: echo "Publishing - ${{ inputs.tag }}"
